"""
Test Esclarecimento Feature - v25
Tests for the new Janela ANVISA esclarecimento (technical clarification) functionality.

Features tested:
1. POST /api/anvisa/esclarecimento - Generate clarification text
2. POST /api/anvisa/atualizar - Background processing
3. GET /api/anvisa/alertas - Alerts sorted by indice_oportunidade
"""
import pytest
import requests
import os
import time

BASE_URL = os.environ.get('REACT_APP_BACKEND_URL', '').rstrip('/')

class TestEsclarecimentoAPI:
    """Tests for esclarecimento (technical clarification) endpoint"""
    
    def test_esclarecimento_with_empresa_c1(self):
        """
        POST /api/anvisa/esclarecimento generates text with empresa data when empresa_id=c1
        Should include company name, CNPJ, and medicine info
        """
        payload = {
            'medicamento': 'CANABIDIOL',
            'principio_ativo': 'Canabidiol',
            'situacao': 'Desabastecimento confirmado',
            'link_prova': 'https://www.in.gov.br/web/dou/-/resolucao-re-n-1234',
            'tipo_alerta': 'desabastecimento',
            'empresa_id': 'c1'
        }
        
        response = requests.post(f"{BASE_URL}/api/anvisa/esclarecimento", json=payload, timeout=60)
        
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        
        data = response.json()
        
        # Verify response structure
        assert 'texto' in data, "Response should have 'texto' field"
        assert 'medicamento' in data, "Response should have 'medicamento' field"
        assert 'empresa' in data, "Response should have 'empresa' field"
        assert 'empresa_cnpj' in data, "Response should have 'empresa_cnpj' field"
        assert 'gerado_em' in data, "Response should have 'gerado_em' field"
        
        # Verify text content includes medicine name
        texto = data.get('texto', '')
        assert len(texto) > 100, f"Generated text should be substantial, got {len(texto)} chars"
        assert 'CANABIDIOL' in texto.upper() or 'Canabidiol' in texto, "Text should mention the medicine"
        
        # Verify empresa data is included (c1 is HC IMPORTAÇÕES EXPORTAÇÕES LTDA)
        empresa_nome = data.get('empresa', '')
        assert empresa_nome != '', "Empresa name should not be empty"
        print(f"✅ Empresa name: {empresa_nome}")
        
        empresa_cnpj = data.get('empresa_cnpj', '')
        assert empresa_cnpj != '', "Empresa CNPJ should not be empty"
        print(f"✅ Empresa CNPJ: {empresa_cnpj}")
        
        # Check if text includes company data
        assert empresa_nome in texto or empresa_cnpj in texto or 'HC' in texto or 'CNPJ' in texto, \
            "Text should include company name or CNPJ"
        
        print(f"✅ Generated text length: {len(texto)} chars")
        print(f"✅ Generated by: {data.get('gerado_por', 'unknown')}")
    
    def test_esclarecimento_empty_medicamento_returns_error(self):
        """
        POST /api/anvisa/esclarecimento returns error when medicamento is empty
        """
        payload = {
            'medicamento': '',  # Empty medicamento
            'principio_ativo': 'Teste',
            'situacao': 'Teste',
            'link_prova': '',
            'tipo_alerta': 'desabastecimento',
            'empresa_id': 'c1'
        }
        
        response = requests.post(f"{BASE_URL}/api/anvisa/esclarecimento", json=payload, timeout=30)
        
        assert response.status_code == 400, f"Expected 400 for empty medicamento, got {response.status_code}"
        
        data = response.json()
        assert 'detail' in data, "Error response should have 'detail' field"
        print(f"✅ Error message: {data.get('detail')}")
    
    def test_esclarecimento_without_empresa(self):
        """
        POST /api/anvisa/esclarecimento with no empresa_id should still generate template
        """
        payload = {
            'medicamento': 'INSULINA',
            'principio_ativo': 'Insulina Glargina',
            'situacao': 'Desabastecimento',
            'link_prova': 'https://anvisa.gov.br/exemplo',
            'tipo_alerta': 'desabastecimento',
            'empresa_id': ''  # No empresa selected
        }
        
        response = requests.post(f"{BASE_URL}/api/anvisa/esclarecimento", json=payload, timeout=30)
        
        assert response.status_code == 200, f"Expected 200, got {response.status_code}"
        
        data = response.json()
        assert 'texto' in data, "Response should have 'texto' field"
        
        texto = data.get('texto', '')
        assert 'INSULINA' in texto.upper(), "Text should mention the medicine"
        print(f"✅ Generated template without empresa: {len(texto)} chars")


class TestAnvisaAtualizarEndpoint:
    """Tests for ANVISA atualizar (background scraper) endpoint"""
    
    def test_atualizar_returns_immediately_with_processando(self):
        """
        POST /api/anvisa/atualizar returns immediately with status=processando
        Should not block - scraper runs in background
        """
        start_time = time.time()
        
        response = requests.post(f"{BASE_URL}/api/anvisa/atualizar", timeout=10)
        
        elapsed_time = time.time() - start_time
        
        # Should return quickly (under 5 seconds), not waiting for scraper
        assert elapsed_time < 10, f"Endpoint should return quickly (background processing), took {elapsed_time:.2f}s"
        
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        
        data = response.json()
        assert 'status' in data, "Response should have 'status' field"
        assert data.get('status') == 'processando', f"Status should be 'processando', got {data.get('status')}"
        
        print(f"✅ Returned in {elapsed_time:.2f}s with status={data.get('status')}")
        print(f"✅ Message: {data.get('mensagem', 'N/A')}")


class TestAnvisaAlertasSorted:
    """Tests for ANVISA alertas endpoint sorting"""
    
    def test_alertas_sorted_by_indice_oportunidade(self):
        """
        GET /api/anvisa/alertas returns alerts sorted by indice_oportunidade descending
        """
        response = requests.get(f"{BASE_URL}/api/anvisa/alertas", timeout=30)
        
        assert response.status_code == 200, f"Expected 200, got {response.status_code}"
        
        data = response.json()
        assert 'alertas' in data, "Response should have 'alertas' field"
        
        alertas = data.get('alertas', [])
        
        if len(alertas) < 2:
            pytest.skip("Need at least 2 alerts to verify sorting")
        
        # Extract indice_oportunidade values
        indices = [a.get('indice_oportunidade', 0) for a in alertas]
        
        # Verify descending order
        for i in range(len(indices) - 1):
            assert indices[i] >= indices[i+1], \
                f"Alerts should be sorted by indice_oportunidade DESC. Found {indices[i]} before {indices[i+1]} at position {i}"
        
        print(f"✅ Found {len(alertas)} alerts")
        print(f"✅ Top 5 indices: {indices[:5]}")
        print(f"✅ Correctly sorted by indice_oportunidade (descending)")
    
    def test_alertas_include_required_fields(self):
        """
        GET /api/anvisa/alertas includes required fields for UI display
        """
        response = requests.get(f"{BASE_URL}/api/anvisa/alertas", timeout=30)
        
        assert response.status_code == 200
        
        data = response.json()
        alertas = data.get('alertas', [])
        
        if len(alertas) == 0:
            pytest.skip("No alerts to verify")
        
        # Check first alert has required fields
        alerta = alertas[0]
        required_fields = ['medicamento', 'situacao', 'risco', 'tipo_alerta', 'indice_oportunidade']
        
        for field in required_fields:
            assert field in alerta, f"Alert should have '{field}' field"
        
        print(f"✅ Alert fields verified: {list(alerta.keys())}")


class TestEmpresasAPI:
    """Tests for empresas endpoint used by esclarecimento modal"""
    
    def test_empresas_returns_list(self):
        """
        GET /api/empresas returns list of companies
        """
        response = requests.get(f"{BASE_URL}/api/empresas", timeout=10)
        
        assert response.status_code == 200, f"Expected 200, got {response.status_code}"
        
        data = response.json()
        assert 'empresas' in data, "Response should have 'empresas' field"
        
        empresas = data.get('empresas', [])
        print(f"✅ Found {len(empresas)} empresas")
        
        # Check if c1 (HC IMPORTAÇÕES) exists
        c1 = next((e for e in empresas if e.get('id') == 'c1'), None)
        if c1:
            print(f"✅ c1: {c1.get('name')} - CNPJ: {c1.get('cnpj')}")
            assert 'name' in c1, "Empresa should have 'name'"
            assert 'cnpj' in c1, "Empresa should have 'cnpj'"
        
        # Check if c2 (Smart Medical) exists
        c2 = next((e for e in empresas if e.get('id') == 'c2'), None)
        if c2:
            print(f"✅ c2: {c2.get('name')} - CNPJ: {c2.get('cnpj')}")


# Allow running tests directly
if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
